### ISSUE TITLE
Phenopacket export

### ISSUE THREAD

**Issue by ielis** [monarch-initiative/HpoCaseAnnotator#42]
When we export `Phenopacket` from the internal format, we have:

```json
"diseases": [{
    "term": {
      "id": "OMIM:306400",
      "label": "GRANULOMATOUS DISEASE, CHRONIC, X-LINKED; CGD"
    }
  }]
```

for the disease, and

```json
"genes": [{
    "id": "ENTREZ:1536",
    "symbol": "CYBB"
  }]
```

 However, I do not know how to create appropriate `Resource` for these namespaces (OMIM, ENTREZ).

@pnrobinson do you please have any suggestions how to fix it? Otherwise the `Phenopacket` will not be valid, at least by the code I wrote this morning..

**Comment by julesjacobsen** [comment]
Like this?
```yaml
- id: "omim"
    name: "Online Mendelian Inheritance in Man"
    namespacePrefix: "OMIM"
    url: "https://omim.org"
    iriPrefix: "https://omim.org/entry/"
```

in the Monarch curie map OMIM is defined as
```properties
'OMIM' : 'http://purl.obolibrary.org/obo/OMIM_'  # OMIM: Online Mendelian Inheritance in Man (human disease and variants)
```
Which doesn't resolve to anything, so I'd like to know what they are doing.
